server:
  port: 8888

logging:
  level:
   # com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: DEBUG
    
spring:
  cloud:
    config:     
      server:
        git:
          uri: https://github.com/ishwar1987/config-server-repo.git
             
management:
  security:
    enabled: false